# Generated by Django 3.2.9 on 2022-01-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_address_studentmodel_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='city',
            new_name='address',
        ),
    ]
