# Generated by Django 3.2.9 on 2022-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_city_studentmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
