# Generated by Django 3.2.9 on 2022-01-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='username',
        ),
    ]
